import AboutMe from '@/components/Home/AboutMe'
import Hero from '@/components/Home/Hero'
import Layout from '@/components/Layout'
import Head from 'next/head'

export default function Home () {
  return (
    <Layout title='Home'>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Hero />
        <AboutMe />
      </main>
    </Layout>
  )
}
